name: Create pull request of master to develop

on:
  push:
    branches: [ main ]

jobs:
  create-pull-request:
    name: Create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: vsoch/pull-request-action@1.0.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_TITLE: Sync master and develop
          PULL_REQUEST_BODY: Sync master and develop
