name: Create pull request or add reviewer

on:
  pull_request:
    types: opened

jobs:
  create-pull-request-or-add-reviewer:
    runs-on: ubuntu-latest
    steps:
    - name: Request review
      uses: murs313/request-review@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: ${{ github.actor }}
